# This is an autogenerated file for your Rails::Application subclass

# typed: strong
class Hogwarts_5_0::Application
end

class Rails
  extend T::Sig

  sig { returns(Hogwarts_5_0::Application) }
  def self.application
  end
end
