# typed: strong
# This is an autogenerated file for Rails helpers.
# Please rerun rake rails_rbi:mailers to regenerate.
class HogwartsAcceptanceMailer
  sig { params(student: Wizard).returns(ActionMailer::MessageDelivery) }
  def self.notify(student); end

  sig { params(student: T.untyped).returns(ActionMailer::MessageDelivery) }
  def self.notify_retry(student); end
end
