# This is an autogenerated file for routes helper methods

# typed: strong
class ActionController::Base
  extend T::Sig

  # Sigs for route /test/index(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def test_index_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def test_index_url(*args, **kwargs); end

end
