# This is an autogenerated file for your Rails::Application subclass

# typed: strong
class Hogwarts_5_17::Application < Rails::Application
end

module Rails
  extend T::Sig

  sig { returns(Hogwarts_5_17::Application) }
  def self.application; end
end
