fixes:
 - "spec/support/v*/app/controllers::spec/support/rails_shared/app/controllers"
 - "spec/support/v*/app/models::spec/support/rails_shared/app/models"
 - "spec/support/v*/config/routes.rb::spec/support/rails_shared/config/routes.rb"
