# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_11; end
module ::Anonymous_Delegator_18; end
module ::Anonymous_Delegator_25; end
module ::Anonymous_Delegator_4; end
