# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rails-deprecated_sanitizer/all/rails-deprecated_sanitizer.rbi
#
# rails-deprecated_sanitizer-1.0.3
module HTML
  extend ActiveSupport::Autoload
end
