# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rdoc/all/rdoc.rbi
#
# rdoc-4.3.0
module RDoc
  def self.load_yaml; end
end
class RDoc::Error < RuntimeError
end
class RDoc::Markup
  def add_html(tag, name); end
  def add_special(pattern, name); end
  def add_word_pair(start, stop, name); end
  def attribute_manager; end
  def convert(input, formatter); end
  def initialize(attribute_manager = nil); end
  def self.parse(str); end
end
class RDoc::Markup::Formatter
  def accept_document(document); end
  def add_special_RDOCLINK; end
  def add_special_TIDYLINK; end
  def add_tag(name, start, stop); end
  def annotate(tag); end
  def convert(content); end
  def convert_flow(flow); end
  def convert_special(special); end
  def convert_string(string); end
  def ignore(*node); end
  def in_tt?; end
  def initialize(options, markup = nil); end
  def off_tags(res, item); end
  def on_tags(res, item); end
  def parse_url(url); end
  def self.gen_relative_url(path, target); end
  def tt?(tag); end
end
class RDoc::Markup::Formatter::InlineTag < Struct
  def bit; end
  def bit=(_); end
  def off; end
  def off=(_); end
  def on; end
  def on=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class RDoc::Markup::ToJoinedParagraph < RDoc::Markup::Formatter
  def accept_block_quote(*node); end
  def accept_heading(*node); end
  def accept_list_end(*node); end
  def accept_list_item_end(*node); end
  def accept_list_item_start(*node); end
  def accept_list_start(*node); end
  def accept_paragraph(paragraph); end
  def accept_raw(*node); end
  def accept_rule(*node); end
  def accept_verbatim(*node); end
  def end_accepting; end
  def initialize; end
  def start_accepting; end
end
class RDoc::Markdown::Literals
  def _Alphanumeric; end
  def _AlphanumericAscii; end
  def _BOM; end
  def _Newline; end
  def _NonAlphanumeric; end
  def _Spacechar; end
  def apply(rule); end
  def apply_with_args(rule, *args); end
  def current_column(target = nil); end
  def current_line(target = nil); end
  def external_invoke(other, rule, *args); end
  def failed_rule; end
  def failing_rule_offset; end
  def failure_caret; end
  def failure_character; end
  def failure_info; end
  def failure_oneline; end
  def get_byte; end
  def get_text(start); end
  def grow_lr(rule, args, start_pos, m); end
  def initialize(str, debug = nil); end
  def lines; end
  def match_string(str); end
  def parse(rule = nil); end
  def pos; end
  def pos=(arg0); end
  def raise_error; end
  def result; end
  def result=(arg0); end
  def scan(reg); end
  def self.rule_info(name, rendered); end
  def set_failed_rule(name); end
  def set_string(string, pos); end
  def setup_foreign_grammar; end
  def setup_parser(str, debug = nil); end
  def show_error(io = nil); end
  def show_pos; end
  def string; end
end
class RDoc::Markdown::Literals::ParseError < RuntimeError
end
class RDoc::Markdown::Literals::MemoEntry
  def ans; end
  def initialize(ans, pos); end
  def left_rec; end
  def left_rec=(arg0); end
  def move!(ans, pos, result); end
  def pos; end
  def result; end
  def set; end
end
class RDoc::Markdown::Literals::RuleInfo
  def initialize(name, rendered); end
  def name; end
  def rendered; end
end
class RDoc::Markdown
  def _Alphanumeric; end
  def _AlphanumericAscii; end
  def _AtxHeading; end
  def _AtxInline; end
  def _AtxStart; end
  def _AutoLink; end
  def _AutoLinkEmail; end
  def _AutoLinkUrl; end
  def _BOM; end
  def _BlankLine; end
  def _Block; end
  def _BlockQuote; end
  def _BlockQuoteRaw; end
  def _Bullet; end
  def _BulletList; end
  def _CharEntity; end
  def _Code; end
  def _CodeFence; end
  def _DecEntity; end
  def _DefinitionList; end
  def _DefinitionListDefinition; end
  def _DefinitionListItem; end
  def _DefinitionListLabel; end
  def _Digit; end
  def _Doc; end
  def _Emph; end
  def _EmphStar; end
  def _EmphUl; end
  def _EmptyTitle; end
  def _Endline; end
  def _Entity; end
  def _Enumerator; end
  def _Eof; end
  def _EscapedChar; end
  def _ExplicitLink; end
  def _ExtendedSpecialChar; end
  def _Heading; end
  def _HexEntity; end
  def _HorizontalRule; end
  def _HtmlAnchor; end
  def _HtmlAttribute; end
  def _HtmlBlock; end
  def _HtmlBlockAddress; end
  def _HtmlBlockBlockquote; end
  def _HtmlBlockCenter; end
  def _HtmlBlockCloseAddress; end
  def _HtmlBlockCloseBlockquote; end
  def _HtmlBlockCloseCenter; end
  def _HtmlBlockCloseDd; end
  def _HtmlBlockCloseDir; end
  def _HtmlBlockCloseDiv; end
  def _HtmlBlockCloseDl; end
  def _HtmlBlockCloseDt; end
  def _HtmlBlockCloseFieldset; end
  def _HtmlBlockCloseForm; end
  def _HtmlBlockCloseFrameset; end
  def _HtmlBlockCloseH1; end
  def _HtmlBlockCloseH2; end
  def _HtmlBlockCloseH3; end
  def _HtmlBlockCloseH4; end
  def _HtmlBlockCloseH5; end
  def _HtmlBlockCloseH6; end
  def _HtmlBlockCloseLi; end
  def _HtmlBlockCloseMenu; end
  def _HtmlBlockCloseNoframes; end
  def _HtmlBlockCloseNoscript; end
  def _HtmlBlockCloseOl; end
  def _HtmlBlockCloseP; end
  def _HtmlBlockClosePre; end
  def _HtmlBlockCloseScript; end
  def _HtmlBlockCloseTable; end
  def _HtmlBlockCloseTbody; end
  def _HtmlBlockCloseTd; end
  def _HtmlBlockCloseTfoot; end
  def _HtmlBlockCloseTh; end
  def _HtmlBlockCloseThead; end
  def _HtmlBlockCloseTr; end
  def _HtmlBlockCloseUl; end
  def _HtmlBlockDd; end
  def _HtmlBlockDir; end
  def _HtmlBlockDiv; end
  def _HtmlBlockDl; end
  def _HtmlBlockDt; end
  def _HtmlBlockFieldset; end
  def _HtmlBlockForm; end
  def _HtmlBlockFrameset; end
  def _HtmlBlockH1; end
  def _HtmlBlockH2; end
  def _HtmlBlockH3; end
  def _HtmlBlockH4; end
  def _HtmlBlockH5; end
  def _HtmlBlockH6; end
  def _HtmlBlockInTags; end
  def _HtmlBlockLi; end
  def _HtmlBlockMenu; end
  def _HtmlBlockNoframes; end
  def _HtmlBlockNoscript; end
  def _HtmlBlockOl; end
  def _HtmlBlockOpenAddress; end
  def _HtmlBlockOpenBlockquote; end
  def _HtmlBlockOpenCenter; end
  def _HtmlBlockOpenDd; end
  def _HtmlBlockOpenDir; end
  def _HtmlBlockOpenDiv; end
  def _HtmlBlockOpenDl; end
  def _HtmlBlockOpenDt; end
  def _HtmlBlockOpenFieldset; end
  def _HtmlBlockOpenForm; end
  def _HtmlBlockOpenFrameset; end
  def _HtmlBlockOpenH1; end
  def _HtmlBlockOpenH2; end
  def _HtmlBlockOpenH3; end
  def _HtmlBlockOpenH4; end
  def _HtmlBlockOpenH5; end
  def _HtmlBlockOpenH6; end
  def _HtmlBlockOpenLi; end
  def _HtmlBlockOpenMenu; end
  def _HtmlBlockOpenNoframes; end
  def _HtmlBlockOpenNoscript; end
  def _HtmlBlockOpenOl; end
  def _HtmlBlockOpenP; end
  def _HtmlBlockOpenPre; end
  def _HtmlBlockOpenScript; end
  def _HtmlBlockOpenTable; end
  def _HtmlBlockOpenTbody; end
  def _HtmlBlockOpenTd; end
  def _HtmlBlockOpenTfoot; end
  def _HtmlBlockOpenTh; end
  def _HtmlBlockOpenThead; end
  def _HtmlBlockOpenTr; end
  def _HtmlBlockOpenUl; end
  def _HtmlBlockP; end
  def _HtmlBlockPre; end
  def _HtmlBlockScript; end
  def _HtmlBlockSelfClosing; end
  def _HtmlBlockTable; end
  def _HtmlBlockTbody; end
  def _HtmlBlockTd; end
  def _HtmlBlockTfoot; end
  def _HtmlBlockTh; end
  def _HtmlBlockThead; end
  def _HtmlBlockTr; end
  def _HtmlBlockType; end
  def _HtmlBlockUl; end
  def _HtmlCloseAnchor; end
  def _HtmlComment; end
  def _HtmlOpenAnchor; end
  def _HtmlTag; end
  def _HtmlUnclosed; end
  def _HtmlUnclosedType; end
  def _Image; end
  def _InStyleTags; end
  def _Indent; end
  def _IndentedLine; end
  def _Inline; end
  def _InlineNote; end
  def _Inlines; end
  def _Label; end
  def _Line; end
  def _LineBreak; end
  def _Link; end
  def _ListBlock; end
  def _ListBlockLine; end
  def _ListContinuationBlock; end
  def _ListItem; end
  def _ListItemTight; end
  def _ListLoose; end
  def _ListTight; end
  def _Newline; end
  def _NonAlphanumeric; end
  def _NonblankIndentedLine; end
  def _NonindentSpace; end
  def _Nonspacechar; end
  def _NormalChar; end
  def _NormalEndline; end
  def _Note; end
  def _NoteReference; end
  def _Notes; end
  def _OneStarClose; end
  def _OneStarOpen; end
  def _OneUlClose; end
  def _OneUlOpen; end
  def _OptionallyIndentedLine; end
  def _OrderedList; end
  def _Para; end
  def _Plain; end
  def _Quoted; end
  def _RawHtml; end
  def _RawLine; end
  def _RawNoteBlock; end
  def _RawNoteReference; end
  def _RefSrc; end
  def _RefTitle; end
  def _RefTitleDouble; end
  def _RefTitleParens; end
  def _RefTitleSingle; end
  def _Reference; end
  def _ReferenceLink; end
  def _ReferenceLinkDouble; end
  def _ReferenceLinkSingle; end
  def _References; end
  def _SetextBottom1; end
  def _SetextBottom2; end
  def _SetextHeading1; end
  def _SetextHeading2; end
  def _SetextHeading; end
  def _SkipBlock; end
  def _Source; end
  def _SourceContents; end
  def _Sp; end
  def _Space; end
  def _Spacechar; end
  def _SpecialChar; end
  def _Spnl; end
  def _StarLine; end
  def _StartList; end
  def _Str; end
  def _StrChunk; end
  def _Strong; end
  def _StrongStar; end
  def _StrongUl; end
  def _StyleBlock; end
  def _StyleClose; end
  def _StyleOpen; end
  def _Symbol; end
  def _TerminalEndline; end
  def _Ticks1; end
  def _Ticks2; end
  def _Ticks3; end
  def _Ticks4; end
  def _Ticks5; end
  def _Title; end
  def _TitleDouble; end
  def _TitleSingle; end
  def _TwoStarClose; end
  def _TwoStarOpen; end
  def _TwoUlClose; end
  def _TwoUlOpen; end
  def _UlLine; end
  def _UlOrStarLine; end
  def _Verbatim; end
  def _VerbatimChunk; end
  def _root; end
  def apply(rule); end
  def apply_with_args(rule, *args); end
  def break_on_newline=(enable); end
  def break_on_newline?; end
  def css=(enable); end
  def css?; end
  def current_column(target = nil); end
  def current_line(target = nil); end
  def definition_lists=(enable); end
  def definition_lists?; end
  def emphasis(text); end
  def extension(name, enable); end
  def extension?(name); end
  def external_invoke(other, rule, *args); end
  def failed_rule; end
  def failing_rule_offset; end
  def failure_caret; end
  def failure_character; end
  def failure_info; end
  def failure_oneline; end
  def get_byte; end
  def get_text(start); end
  def github=(enable); end
  def github?; end
  def grow_lr(rule, args, start_pos, m); end
  def html=(enable); end
  def html?; end
  def initialize(extensions = nil, debug = nil); end
  def inner_parse(text); end
  def lines; end
  def link_to(content, label = nil, text = nil); end
  def list_item_from(unparsed); end
  def match_string(str); end
  def note(label); end
  def note_for(ref); end
  def notes=(enable); end
  def notes?; end
  def orig_initialize(str, debug = nil); end
  def paragraph(parts); end
  def parse(markdown); end
  def peg_parse(rule = nil); end
  def pos; end
  def pos=(arg0); end
  def raise_error; end
  def reference(label, link); end
  def result; end
  def result=(arg0); end
  def scan(reg); end
  def self.extension(name); end
  def self.parse(markdown); end
  def self.rule_info(name, rendered); end
  def set_failed_rule(name); end
  def set_string(string, pos); end
  def setup_foreign_grammar; end
  def setup_parser(str, debug = nil); end
  def show_error(io = nil); end
  def show_pos; end
  def string; end
  def strong(text); end
end
class RDoc::Markdown::ParseError < RuntimeError
end
class RDoc::Markdown::MemoEntry
  def ans; end
  def initialize(ans, pos); end
  def left_rec; end
  def left_rec=(arg0); end
  def move!(ans, pos, result); end
  def pos; end
  def result; end
  def set; end
end
class RDoc::Markdown::RuleInfo
  def initialize(name, rendered); end
  def name; end
  def rendered; end
end
class RDoc::RD
  def self.parse(rd); end
end
class RDoc::Markup::Parser
  def build_heading(level); end
  def build_list(margin); end
  def build_paragraph(margin); end
  def build_verbatim(margin); end
  def char_pos(byte_offset); end
  def debug; end
  def debug=(arg0); end
  def get; end
  def initialize; end
  def parse(parent, indent = nil); end
  def parse_text(parent, indent); end
  def peek_token; end
  def self.parse(str); end
  def self.tokenize(str); end
  def setup_scanner(input); end
  def skip(token_type, error = nil); end
  def token_pos(byte_offset); end
  def tokenize(input); end
  def tokens; end
  def unget; end
  include RDoc::Text
end
class RDoc::Markup::Parser::Error < RuntimeError
end
class RDoc::Markup::Parser::ParseError < RDoc::Markup::Parser::Error
end
class RDoc::Markup::PreProcess
  def find_include_file(name); end
  def handle(text, code_object = nil, &block); end
  def handle_directive(prefix, directive, param, code_object = nil, encoding = nil); end
  def include_file(name, indent, encoding); end
  def initialize(input_file_name, include_path); end
  def options; end
  def options=(arg0); end
  def self.post_process(&block); end
  def self.post_processors; end
  def self.register(directive, &block); end
  def self.registered; end
  def self.reset; end
end
class RDoc::TomDoc < RDoc::Markup::Parser
  def build_heading(level); end
  def build_paragraph(margin); end
  def build_verbatim(margin); end
  def initialize; end
  def parse_text(parent, indent); end
  def self.add_post_processor; end
  def self.parse(text); end
  def self.signature(comment); end
  def tokenize(text); end
  def tokens; end
end
module RDoc::Text
  def expand_tabs(text); end
  def flush_left(text); end
  def markup(text); end
  def normalize_comment(text); end
  def parse(text, format = nil); end
  def self.encode_fallback(character, encoding, fallback); end
  def snippet(text, limit = nil); end
  def strip_hashes(text); end
  def strip_newlines(text); end
  def strip_stars(text); end
  def to_html(text); end
  def wrap(txt, line_len = nil); end
end
class RDoc::CodeObject
  def comment; end
  def comment=(comment); end
  def display?; end
  def document_children; end
  def document_children=(document_children); end
  def document_self; end
  def document_self=(document_self); end
  def documented?; end
  def done_documenting; end
  def done_documenting=(value); end
  def each_parent; end
  def file; end
  def file_name; end
  def force_documentation; end
  def force_documentation=(value); end
  def full_name=(full_name); end
  def ignore; end
  def ignored?; end
  def initialize; end
  def initialize_visibility; end
  def line; end
  def line=(arg0); end
  def metadata; end
  def offset; end
  def offset=(arg0); end
  def options; end
  def parent; end
  def parent=(arg0); end
  def parent_file_name; end
  def parent_name; end
  def received_nodoc; end
  def record_location(top_level); end
  def section; end
  def section=(arg0); end
  def start_doc; end
  def stop_doc; end
  def store; end
  def store=(store); end
  def suppress; end
  def suppressed?; end
  def viewer; end
  def viewer=(arg0); end
  include RDoc::Generator::Markup
  include RDoc::Text
end
class RDoc::Context < RDoc::CodeObject
  def <=>(other); end
  def add(klass, name, comment); end
  def add_alias(an_alias); end
  def add_attribute(attribute); end
  def add_class(class_type, given_name, superclass = nil); end
  def add_class_or_module(mod, self_hash, all_hash); end
  def add_constant(constant); end
  def add_extend(ext); end
  def add_include(include); end
  def add_method(method); end
  def add_module(class_type, name); end
  def add_module_alias(from, name, file); end
  def add_require(require); end
  def add_section(title, comment = nil); end
  def add_to(array, thing); end
  def aliases; end
  def any_content(includes = nil); end
  def attributes; end
  def block_params; end
  def block_params=(arg0); end
  def child_name(name); end
  def class_attributes; end
  def class_method_list; end
  def classes; end
  def classes_and_modules; end
  def classes_hash; end
  def constants; end
  def constants_hash; end
  def current_section; end
  def current_section=(arg0); end
  def defined_in?(file); end
  def display(method_attr); end
  def each_ancestor; end
  def each_attribute; end
  def each_classmodule(&block); end
  def each_constant; end
  def each_extend; end
  def each_include; end
  def each_method; end
  def each_section; end
  def extends; end
  def external_aliases; end
  def find_attribute(name, singleton); end
  def find_attribute_named(name); end
  def find_class_method_named(name); end
  def find_constant_named(name); end
  def find_enclosing_module_named(name); end
  def find_external_alias(name, singleton); end
  def find_external_alias_named(name); end
  def find_file_named(name); end
  def find_instance_method_named(name); end
  def find_local_symbol(symbol); end
  def find_method(name, singleton); end
  def find_method_named(name); end
  def find_module_named(name); end
  def find_symbol(symbol); end
  def find_symbol_module(symbol); end
  def full_name; end
  def fully_documented?; end
  def http_url(prefix); end
  def in_files; end
  def includes; end
  def initialize; end
  def initialize_methods_etc; end
  def instance_attributes; end
  def instance_method_list; end
  def method_list; end
  def methods_by_type(section = nil); end
  def methods_hash; end
  def methods_matching(methods, singleton = nil, &block); end
  def modules; end
  def modules_hash; end
  def name; end
  def name_for_path; end
  def ongoing_visibility=(visibility); end
  def params; end
  def params=(arg0); end
  def record_location(top_level); end
  def remove_from_documentation?; end
  def remove_invisible(min_visibility); end
  def remove_invisible_in(array, min_visibility); end
  def requires; end
  def resolve_aliases(added); end
  def section_contents; end
  def sections; end
  def sections_hash; end
  def set_current_section(title, comment); end
  def set_visibility_for(methods, visibility, singleton = nil); end
  def sort_sections; end
  def temporary_section; end
  def temporary_section=(arg0); end
  def to_s; end
  def top_level; end
  def unmatched_alias_lists; end
  def unmatched_alias_lists=(arg0); end
  def upgrade_to_class(mod, class_type, enclosing); end
  def visibility; end
  def visibility=(arg0); end
  include Comparable
end
class RDoc::ClassModule < RDoc::Context
  def add_comment(comment, location); end
  def add_things(my_things, other_things); end
  def ancestors; end
  def aref; end
  def aref_prefix; end
  def clear_comment; end
  def comment=(comment); end
  def comment_location; end
  def comment_location=(arg0); end
  def complete(min_visibility); end
  def constant_aliases; end
  def constant_aliases=(arg0); end
  def description; end
  def diagram; end
  def diagram=(arg0); end
  def direct_ancestors; end
  def document_self_or_methods; end
  def documented?; end
  def each_ancestor; end
  def find_ancestor_local_symbol(symbol); end
  def find_class_named(name); end
  def full_name; end
  def initialize(name, superclass = nil); end
  def is_alias_for; end
  def is_alias_for=(arg0); end
  def marshal_dump; end
  def marshal_load(array); end
  def merge(class_module); end
  def merge_collections(mine, other, other_files, &block); end
  def merge_sections(cm); end
  def module?; end
  def name=(new_name); end
  def name_for_path; end
  def non_aliases; end
  def parse(comment_location); end
  def path; end
  def remove_nodoc_children; end
  def remove_things(my_things, other_files); end
  def search_record; end
  def self.from_module(class_type, mod); end
  def store=(store); end
  def superclass; end
  def superclass=(superclass); end
  def to_s; end
  def type; end
  def update_aliases; end
  def update_extends; end
  def update_includes; end
end
class RDoc::Options
  def ==(other); end
  def charset; end
  def charset=(arg0); end
  def check_files; end
  def check_generator; end
  def coverage_report; end
  def coverage_report=(arg0); end
  def default_title=(string); end
  def dry_run; end
  def dry_run=(arg0); end
  def encode_with(coder); end
  def encoding; end
  def encoding=(arg0); end
  def exclude; end
  def exclude=(arg0); end
  def files; end
  def files=(arg0); end
  def finish; end
  def finish_page_dir; end
  def force_output; end
  def force_output=(arg0); end
  def force_update; end
  def force_update=(arg0); end
  def formatter; end
  def formatter=(arg0); end
  def generator; end
  def generator=(arg0); end
  def generator_descriptions; end
  def generator_name; end
  def generator_options; end
  def generator_options=(arg0); end
  def hyperlink_all; end
  def hyperlink_all=(arg0); end
  def init_ivars; end
  def init_with(map); end
  def initialize; end
  def line_numbers; end
  def line_numbers=(arg0); end
  def locale; end
  def locale=(arg0); end
  def locale_dir; end
  def locale_dir=(arg0); end
  def main_page; end
  def main_page=(arg0); end
  def markup; end
  def markup=(arg0); end
  def op_dir; end
  def op_dir=(arg0); end
  def option_parser; end
  def option_parser=(arg0); end
  def output_decoration; end
  def output_decoration=(arg0); end
  def page_dir; end
  def page_dir=(arg0); end
  def parse(argv); end
  def pipe; end
  def pipe=(arg0); end
  def quiet; end
  def quiet=(bool); end
  def rdoc_include; end
  def rdoc_include=(arg0); end
  def root; end
  def root=(arg0); end
  def sanitize_path(path); end
  def setup_generator(generator_name = nil); end
  def show_hash; end
  def show_hash=(arg0); end
  def static_path; end
  def static_path=(arg0); end
  def tab_width; end
  def tab_width=(arg0); end
  def template; end
  def template=(arg0); end
  def template_dir; end
  def template_dir=(arg0); end
  def template_dir_for(template); end
  def template_stylesheets; end
  def template_stylesheets=(arg0); end
  def title; end
  def title=(arg0); end
  def to_yaml(opts = nil); end
  def update_output_dir; end
  def update_output_dir=(arg0); end
  def verbosity; end
  def verbosity=(arg0); end
  def visibility; end
  def visibility=(visibility); end
  def warn(message); end
  def webcvs; end
  def webcvs=(arg0); end
  def write_options; end
  def yaml_initialize(tag, map); end
end
class RDoc::MethodAttr < RDoc::CodeObject
  def <=>(other); end
  def ==(other); end
  def add_alias(an_alias, context); end
  def add_line_numbers(src); end
  def aliases; end
  def aref; end
  def aref_prefix; end
  def arglists; end
  def block_params; end
  def block_params=(value); end
  def call_seq; end
  def call_seq=(arg0); end
  def documented?; end
  def find_method_or_attribute(name); end
  def find_see; end
  def full_name; end
  def html_name; end
  def initialize(text, name); end
  def initialize_copy(other); end
  def initialize_visibility; end
  def inspect; end
  def is_alias_for; end
  def is_alias_for=(arg0); end
  def markup_code; end
  def name; end
  def name=(arg0); end
  def name_prefix; end
  def output_name(context); end
  def param_seq; end
  def params; end
  def params=(arg0); end
  def parent_name; end
  def path; end
  def pretty_name; end
  def pretty_print(q); end
  def search_record; end
  def see; end
  def self.add_line_numbers; end
  def self.add_line_numbers=(arg0); end
  def singleton; end
  def singleton=(arg0); end
  def store=(store); end
  def text; end
  def to_s; end
  def type; end
  def visibility; end
  def visibility=(arg0); end
  include Comparable
end
module RDoc::TokenStream
  def add_token(*tokens); end
  def add_tokens(*tokens); end
  def collect_tokens; end
  def pop_token; end
  def self.to_html(token_stream); end
  def start_collecting_tokens; end
  def token_stream; end
  def tokens_to_s; end
end
class RDoc::AnyMethod < RDoc::MethodAttr
  def add_alias(an_alias, context = nil); end
  def aref_prefix; end
  def arglists; end
  def c_function; end
  def c_function=(arg0); end
  def call_seq; end
  def call_seq=(call_seq); end
  def calls_super; end
  def calls_super=(arg0); end
  def dont_rename_initialize; end
  def dont_rename_initialize=(arg0); end
  def initialize(text, name); end
  def is_alias_for; end
  def marshal_dump; end
  def marshal_load(array); end
  def name; end
  def param_list; end
  def param_seq; end
  def params; end
  def params=(arg0); end
  def store=(store); end
  def superclass_method; end
  include RDoc::TokenStream
end
module RDoc::Generator
end
class RDoc::Context::Section
  def ==(other); end
  def add_comment(comment); end
  def aref; end
  def comment; end
  def comments; end
  def extract_comment(comment); end
  def in_files; end
  def initialize(parent, title, comment); end
  def inspect; end
  def marshal_dump; end
  def marshal_load(array); end
  def parent; end
  def parse; end
  def plain_html; end
  def remove_comment(comment); end
  def sequence; end
  def title; end
  include RDoc::Generator::Markup
  include RDoc::Text
end
class RDoc::TopLevel < RDoc::Context
  def ==(other); end
  def absolute_name; end
  def absolute_name=(arg0); end
  def add_alias(an_alias); end
  def add_constant(constant); end
  def add_include(include); end
  def add_method(method); end
  def add_to_classes_or_modules(mod); end
  def base_name; end
  def classes_or_modules; end
  def cvs_url; end
  def diagram; end
  def diagram=(arg0); end
  def display?; end
  def eql?(other); end
  def file_stat; end
  def file_stat=(arg0); end
  def find_class_or_module(name); end
  def find_local_symbol(symbol); end
  def find_module_named(name); end
  def full_name; end
  def hash; end
  def http_url(prefix); end
  def initialize(absolute_name, relative_name = nil); end
  def inspect; end
  def last_modified; end
  def marshal_dump; end
  def marshal_load(array); end
  def name; end
  def object_class; end
  def page_name; end
  def parser; end
  def parser=(arg0); end
  def path; end
  def pretty_print(q); end
  def relative_name; end
  def relative_name=(arg0); end
  def search_record; end
  def text?; end
  def to_s; end
end
module RDoc::Generator::Markup
  def aref_to(target_path); end
  def as_href(from_path); end
  def cvs_url(url, full_path); end
  def description; end
  def formatter; end
end
class RDoc::Generator::Darkfish
  def assemble_template(body_file); end
  def asset_rel_path; end
  def asset_rel_path=(arg0); end
  def base_dir; end
  def class_dir; end
  def classes; end
  def copy_static; end
  def debug_msg(*msg); end
  def dry_run; end
  def dry_run=(arg0); end
  def file_dir; end
  def file_output; end
  def file_output=(arg0); end
  def files; end
  def gen_sub_directories; end
  def generate; end
  def generate_class(klass, template_file = nil); end
  def generate_class_files; end
  def generate_file_files; end
  def generate_index; end
  def generate_page(file); end
  def generate_servlet_not_found(message); end
  def generate_servlet_root(installed); end
  def generate_table_of_contents; end
  def get_sorted_module_list(classes); end
  def get_svninfo(klass); end
  def initialize(store, options); end
  def install_rdoc_static_file(source, destination, options); end
  def json_index; end
  def methods; end
  def modsort; end
  def outputdir; end
  def render(file_name); end
  def render_template(template_file, out_file = nil); end
  def setup; end
  def store; end
  def template_dir; end
  def template_for(file, page = nil, klass = nil); end
  def template_result(template, context, template_file); end
  def time_delta_string(seconds); end
  def write_style_sheet; end
  include ERB::Util
end
class RDoc::Generator::RI
  def generate; end
  def initialize(store, options); end
end
class RDoc::Generator::POT
  def class_dir; end
  def extract_messages; end
  def generate; end
  def initialize(store, options); end
end
class RDoc::RDoc
  def document(options); end
  def error(msg); end
  def exclude; end
  def exclude=(arg0); end
  def gather_files(files); end
  def generate; end
  def generator; end
  def generator=(arg0); end
  def handle_pipe; end
  def initialize; end
  def install_siginfo_handler; end
  def last_modified; end
  def list_files_in_directory(dir); end
  def load_options; end
  def normalized_file_list(relative_files, force_doc = nil, exclude_pattern = nil); end
  def options; end
  def options=(arg0); end
  def output_flag_file(op_dir); end
  def parse_dot_doc_file(in_dir, filename); end
  def parse_file(filename); end
  def parse_files(files); end
  def remove_siginfo_handler; end
  def remove_unparseable(files); end
  def self.add_generator(klass); end
  def self.current; end
  def self.current=(rdoc); end
  def setup_output_dir(dir, force); end
  def stats; end
  def store; end
  def store=(store); end
  def update_output_dir(op_dir, time, last = nil); end
end
